### ISSUE TITLE
Is `purs-compile` possibly relevant to this project?

### ISSUE THREAD

**Issue by paluh** [ursi/psnp#5]
Hi @ursi!

Thank for building this tool! I hope I try it in the near future :-)

I think that the _purs-compile_ project seems like a quite promising approach in the context of _psnp_:

https://github.com/joneshf/purs-tools/blob/41a93ac18103d6c4cd02f20cb205e30fb728bd7a/cmd/purs-compile/README.md

What do you think?

**Comment by ursi** [comment]
I'm not sure how relevant it is to this project specifically, but it's **super** relevant to a nice solution for building PureScript with nix build in a development setting. Thanks for showing me this!

**Comment by ursi** [comment]
yikes, I have no idea how to build that with nix.

**Comment by paluh** [comment]
... Maybe not a really elegant but practical _patchElf_ like in [_purescript-easy-nix_](https://github.com/justinwoo/easy-purescript-nix/blob/master/purs/mkPursDerivation.nix#L14) could work - there are [binaries available](https://github.com/joneshf/purs-tools/releases).
I'm really sorry but I don't have a time now to put together something dirty like the above myself.

**Comment by ursi** [comment]
Hmm, I've yet to use those tools, but thanks for the tip. I'm currently looking into leveraging `purs graph` to eliminate what I thought was going to have to be another code gen step. If I get that figured out I revisit building `purs-compile`. I'm also gonna close this issue because it's not really about this project anymore, but feel free to keep talking here.

**Comment by ursi** [comment]
my project is now public at https://github.com/ursi/purs-nix
